language: julia
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq -y
  - sudo apt-get install git r-base r-base-dev r-recommended -y
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("RCall"); Pkg.test("RCall"; coverage=true)'
after_success:
  # - if [ $JULIAVERSION = "julianightlies" ]; julia -e 'cd(Pkg.dir("RCall")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
